// Created by Michael Simms on 3/3/13.
// Copyright (c) 2013 Michael J. Simms. All rights reserved.

// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

#ifndef __BLUETOOTH_SERVICES__
#define __BLUETOOTH_SERVICES__

typedef enum BluetoothService
{
	BT_SERVICE_ALERT_NOTIFICATION =			0X1811,
	BT_SERVICE_BATTERY_SERVICE =			0X180F,
	BT_SERVICE_BLOOD_PRESSURE =				0X1810,
	BT_SERVICE_CURRENT_TIME =				0X1805,
	BT_SERVICE_CYCLING_SPEED_AND_CADENCE =	0X1816,
	BT_SERVICE_CYCLING_POWER =              0x1818,
	BT_SERVICE_DEVICE_INFORMATION =			0X180A,
	BT_SERVICE_GENERIC_ACCESS =				0X1800,
	BT_SERVICE_GENERIC_ATTRIBUTE =			0X1801,
	BT_SERVICE_GLUCOSE =					0X1808,
	BT_SERVICE_HEALTH_THERMOMETER =			0X1809,
	BT_SERVICE_HEART_RATE =					0X180D,
	BT_SERVICE_HUMAN_INTERFACE_DEVICE =		0X1812,
	BT_SERVICE_IMMEDIATE_ALERT =			0X1802,
	BT_SERVICE_LINK_LOSS =					0X1803,
	BT_SERVICE_NEXT_DST_CHANGE =			0X1807,
	BT_SERVICE_PHONE_ALERT_STATUS =			0X180E,
	BT_SERVICE_REFERENCE_TIME_UPDATE =		0X1806,
	BT_SERVICE_RUNNING_SPEED_AND_CADENCE =	0X1814,
	BT_SERVICE_SCAN_PARAMETERS =			0X1813,
	BT_SERVICE_TX_POWER =					0X1804,
	BT_SERVICE_WEIGHT =                     0x1901
} BluetoothService;

#endif
