// Created by Michael Simms on 7/15/12.
// Copyright (c) 2012 Michael J. Simms. All rights reserved.

#define NOTIFICATION_NAME_ACTIVITY_STARTED         "ActivityStarted"
#define NOTIFICATION_NAME_ACTIVITY_STOPPED         "ActivityStopped"
#define NOTIFICATION_NAME_FRIEND_LOCATION_UPDATED  "FriendLocationUpdated"
#define NOTIFICATION_NAME_GEAR_LIST_UPDATED        "GearListUpdated"
#define NOTIFICATION_NAME_PLANNED_WORKOUTS_UPDATED "PlannedWorkoutsUpdated"
#define NOTIFICATION_NAME_WORKOUT_UPDATED          "WorkoutUpdated"
#define NOTIFICATION_NAME_FRIENDS_LIST_UPDATED     "FriendsListUpdated"
#define NOTIFICATION_NAME_LOGIN_PROCESSED          "LoginProcessed"
#define NOTIFICATION_NAME_CREATE_LOGIN_PROCESSED   "CreateLoginProcessed"
#define NOTIFICATION_NAME_LOGIN_CHECKED            "LoginChecked"
#define NOTIFICATION_NAME_LOGGED_OUT               "LogoutProcessed"
#define NOTIFICATION_NAME_REQUEST_TO_FOLLOW_RESULT "RequestToFollowResult"
#define NOTIFICATION_NAME_PRINT_MESSAGE            "PrintMessage"
#define NOTIFICATION_NAME_BROADCAST_STATUS         "BroadcastStatus"
#define NOTIFICATION_NAME_HAS_ACTIVITY_RESPONSE    "HasActivityResponse"

#define KEY_NAME_ACTIVITY_ID                       "ActivityId"
#define KEY_NAME_ACTIVITY_TYPE                     "ActivityType"
#define KEY_NAME_ACTIVITY_HASH                     "ActivityHash"
#define KEY_NAME_START_TIME                        "StartTime"
#define KEY_NAME_END_TIME                          "EndTime"
#define KEY_NAME_DISTANCE                          "Distance"
#define KEY_NAME_CALORIES                          "Calories"
#define KEY_NAME_RESPONSE_CODE                     "ResponseCode"
#define KEY_NAME_RESPONSE_STR                      "ResponseStr"
#define KEY_NAME_DATA                              "Data"
#define KEY_NAME_URL                               "URL"
#define KEY_NAME_TAG                               "Tag"
#define KEY_NAME_MESSAGE                           "Message"
#define KEY_NAME_STATUS                            "Status"

#define NOTIFICATION_NAME_INTERVAL_UPDATED         "IntervalUpdated"
#define NOTIFICATION_NAME_INTERVAL_COMPLETE        "IntervalComplete"

#define KEY_NAME_DEVICE_ID                         "DeviceId"
#define KEY_NAME_USER_NAME                         "Name"
#define KEY_NAME_INTERVAL_SEGMENT                  "IntervalSegment"

#define KEY_NAME_ACTIVITY_ID2                      "activity_id"
#define KEY_NAME_ACTIVITY_HASH2                    "activity_hash"
#define KEY_NAME_DEVICE_ID2                        "device_id"
#define KEY_NAME_TAG2                              "tag"
#define KEY_NAME_CODE                              "code"
#define KEY_NAME_WEIGHT                            "weight"
#define KEY_NAME_UPLOADED_FILE_NAME                "uploaded_file_name"
#define KEY_NAME_UPLOADED_FILE_DATA                "uploaded_file_data"

#define KEY_NAME_TARGET_EMAIL                      "target_email"
#define KEY_NAME_USERNAME                          "username"
#define KEY_NAME_PASSWORD                          "password"
#define KEY_NAME_PASSWORD1                         "password1"
#define KEY_NAME_PASSWORD2                         "password2"
#define KEY_NAME_REALNAME                          "realname"
#define KEY_NAME_DEVICE                            "device"

#define KEY_NAME_GEAR_TYPE                         "type"
#define KEY_NAME_GEAR_NAME                         "name"
#define KEY_NAME_GEAR_DESCRIPTION                  "description"
#define KEY_NAME_ADD_TIME                          "add_time"
#define KEY_NAME_RETIRE_TIME                       "retire_time"

#define KEY_NAME_WORKOUT_ID                        "workout_id"
#define KEY_NAME_WORKOUT_WORKOUT_TYPE              "type"
#define KEY_NAME_WORKOUT_SPORT_TYPE                "sport type"
#define KEY_NAME_WORKOUT_URL                       "url"
#define KEY_NAME_WORKOUT_SCHEDULED_TIME            "scheduled time"
#define KEY_NAME_WORKOUT_ESTIMATED_STRESS          "estimated stress score"
#define KEY_NAME_WORKOUT_WARMUP                    "warmup"
#define KEY_NAME_WORKOUT_COOLDOWN                  "cooldown"
#define KEY_NAME_WORKOUT_INTERVALS                 "intervals"
#define KEY_NAME_WORKOUT_INTERVAL_REPEAT           "repeat"
#define KEY_NAME_WORKOUT_PACE                      "Pace"
#define KEY_NAME_WORKOUT_DISTANCE                  "Distance"
#define KEY_NAME_WORKOUT_RECOVERY_PACE             "Recovery Pace"
#define KEY_NAME_WORKOUT_RECOVERY_DISTANCE         "Recovery Distance"
