// Created by Michael Simms on 9/24/18.
// Copyright (c) 2018 Michael J. Simms. All rights reserved.

// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

#define STR_OK                NSLocalizedString(@"Ok", nil)
#define STR_YES               NSLocalizedString(@"Yes", nil)
#define STR_NO                NSLocalizedString(@"No", nil)
#define STR_ON                NSLocalizedString(@"On", nil)
#define STR_OFF               NSLocalizedString(@"Off", nil)
#define STR_START             NSLocalizedString(@"Start", nil)
#define STR_STOP              NSLocalizedString(@"Stop", nil)
#define STR_CANCEL            NSLocalizedString(@"Cancel", nil)
#define STR_PAUSE             NSLocalizedString(@"Pause", nil)
#define STR_RESUME            NSLocalizedString(@"Resume", nil)
#define STR_LAP               NSLocalizedString(@"Lap", nil)

#define STR_ATTRIBUTES        NSLocalizedString(@"Attributes", nil)
#define STR_AUTHENTICATION    NSLocalizedString(@"Authentication", nil)
#define STR_AUTOSCALE         NSLocalizedString(@"Autoscale", nil)
#define STR_BIGGEST           NSLocalizedString(@"Biggest", nil)
#define STR_BIKE              NSLocalizedString(@"Bike", nil)
#define STR_CAUTION           NSLocalizedString(@"Caution", nil)
#define STR_CONTINUE          NSLocalizedString(@"Continue", nil)
#define STR_DELETE            NSLocalizedString(@"Delete", nil)
#define STR_EDIT              NSLocalizedString(@"Edit", nil)
#define STR_ERROR             NSLocalizedString(@"Error", nil)
#define STR_EXPORT            NSLocalizedString(@"Export", nil)
#define STR_FASTEST           NSLocalizedString(@"Fastest", nil)
#define STR_FINISHED          NSLocalizedString(@"Finished", nil)
#define STR_FITNESS           NSLocalizedString(@"Fitness", nil)
#define STR_FTP               NSLocalizedString(@"FTP", nil)
#define STR_GENDER            NSLocalizedString(@"Gender", nil)
#define STR_GENERATE          NSLocalizedString(@"Generate", nil)
#define STR_HEIGHT            NSLocalizedString(@"Height", nil)
#define STR_HOME              NSLocalizedString(@"Home", nil)
#define STR_MAP               NSLocalizedString(@"Map", nil)
#define STR_NEXT              NSLocalizedString(@"Next", nil)
#define STR_NONE              NSLocalizedString(@"None", nil)
#define STR_NOT_SYNCHED       NSLocalizedString(@"Not Synched", nil)
#define STR_PROFILE           NSLocalizedString(@"Profile", nil)
#define STR_PREVIOUS          NSLocalizedString(@"Previous", nil)
#define STR_REPLACE           NSLocalizedString(@"Replace", nil)
#define STR_SCALE             NSLocalizedString(@"Scale", nil)
#define STR_STARTED           NSLocalizedString(@"Started", nil)
#define STR_SUMMARY           NSLocalizedString(@"Summary", nil)
#define STR_SYNCHED           NSLocalizedString(@"Synched", nil)
#define STR_TIME              NSLocalizedString(@"Time", nil)
#define STR_WEIGHT            NSLocalizedString(@"Weight", nil)
#define STR_WORKOUT           NSLocalizedString(@"Workout", nil)
#define STR_WORKOUTS          NSLocalizedString(@"Workouts", nil)

#define STR_SECONDS           NSLocalizedString(@"Seconds", nil)
#define STR_METERS            NSLocalizedString(@"Meters", nil)
#define STR_KILOMETERS        NSLocalizedString(@"Kilometers", nil)
#define STR_FEET              NSLocalizedString(@"Feet", nil)
#define STR_YARDS             NSLocalizedString(@"Yards", nil)
#define STR_MILES             NSLocalizedString(@"Miles", nil)
#define STR_SETS              NSLocalizedString(@"Sets", nil)
#define STR_REPS              NSLocalizedString(@"Reps", nil)

#define STR_TAG               NSLocalizedString(@"Tag", nil)
#define STR_TAGS              NSLocalizedString(@"Tags", nil)
#define STR_NEW_TAG           NSLocalizedString(@"New Tag", nil)

#define STR_LOGIN             NSLocalizedString(@"Login", nil)
#define STR_LOGOUT            NSLocalizedString(@"Log Out", nil)

#define STR_RESET_PREFS       NSLocalizedString(@"Reset Settings", nil)
#define STR_RESET_DATA        NSLocalizedString(@"Reset Data", nil)

#define STR_NOT_SET           NSLocalizedString(@"Not Set", nil)

#define SUMMARY_ATTRIBUTE_TOTAL_DISTANCE NSLocalizedString(@"Total Distance", nil)
#define SUMMARY_ATTRIBUTE_MAX_DISTANCE   NSLocalizedString(@"Max. Distance", nil)
#define SUMMARY_ATTRIBUTE_TOTAL_CALORIES NSLocalizedString(@"Total Calories", nil)
#define SUMMARY_ATTRIBUTE_TOTAL_REPS     NSLocalizedString(@"Total Reps", nil)

#define MSG_NO_WORKOUTS                  NSLocalizedString(@"You have not done any workouts.\nGet moving!", nil)
#define MSG_IN_PROGRESS                  NSLocalizedString(@"An unfinished activity has been found. Do you wish to resume it?", nil)
#define MSG_NO_INTERVAL_WORKOUTS         NSLocalizedString(@"No interval workouts have been created.", nil)

#define MSG_LOW_MEMORY        NSLocalizedString(@"Low memory", nil)
#define MSG_MAIL_DISABLED     NSLocalizedString(@"Sending mail is disabled.", nil)
#define MSG_INTERNAL_ERROR    NSLocalizedString(@"Internal error.", nil)
#define MSG_EXPORT_FAILED     NSLocalizedString(@"Export failed!", nil)
#define MSG_EXPORT_SUCCEEDED  NSLocalizedString(@"Export succeeded!", nil)
