// Created by Michael Simms on 9/24/18.
// Copyright (c) 2018 Michael J. Simms. All rights reserved.

// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

#define STR_OK                    NSLocalizedString(@"Ok", nil)
#define STR_YES                   NSLocalizedString(@"Yes", nil)
#define STR_NO                    NSLocalizedString(@"No", nil)
#define STR_ON                    NSLocalizedString(@"On", nil)
#define STR_OFF                   NSLocalizedString(@"Off", nil)
#define STR_START                 NSLocalizedString(@"Start", nil)
#define STR_STOP                  NSLocalizedString(@"Stop", nil)
#define STR_CANCEL                NSLocalizedString(@"Cancel", nil)
#define STR_PAUSE                 NSLocalizedString(@"Pause", nil)
#define STR_RESUME                NSLocalizedString(@"Resume", nil)
#define STR_LAP                   NSLocalizedString(@"Lap", nil)

#define STR_ATTRIBUTES            NSLocalizedString(@"Attributes", nil)
#define STR_AUTHENTICATION        NSLocalizedString(@"Authentication", nil)
#define STR_AUTOSCALE             NSLocalizedString(@"Autoscale", nil)
#define STR_BIGGEST               NSLocalizedString(@"Biggest", nil)
#define STR_BICYCLE               NSLocalizedString(@"Bicycle", nil)
#define STR_BICYCLES              NSLocalizedString(@"Bicycles", nil)
#define STR_BIKE                  NSLocalizedString(@"Bike", nil)
#define STR_CAUTION               NSLocalizedString(@"Caution", nil)
#define STR_CONTINUE              NSLocalizedString(@"Continue", nil)
#define STR_DELETE                NSLocalizedString(@"Delete", nil)
#define STR_DISTANCE              NSLocalizedString(@"Distance", nil)
#define STR_EDIT                  NSLocalizedString(@"Edit", nil)
#define STR_ERROR                 NSLocalizedString(@"Error", nil)
#define STR_EXPORT                NSLocalizedString(@"Export", nil)
#define STR_FASTEST               NSLocalizedString(@"Fastest", nil)
#define STR_FINISHED              NSLocalizedString(@"Finished", nil)
#define STR_FITNESS               NSLocalizedString(@"Fitness", nil)
#define STR_FTP                   NSLocalizedString(@"FTP", nil)
#define STR_GEAR                  NSLocalizedString(@"Gear", nil)
#define STR_GENDER                NSLocalizedString(@"Gender", nil)
#define STR_GENERATE              NSLocalizedString(@"Generate", nil)
#define STR_GOAL                  NSLocalizedString(@"Goal", nil)
#define STR_GOAL_DATE             NSLocalizedString(@"Goal Date", nil)
#define STR_GOAL_TYPE             NSLocalizedString(@"Goal Type", nil)
#define STR_HEIGHT                NSLocalizedString(@"Height", nil)
#define STR_HOME                  NSLocalizedString(@"Home", nil)
#define STR_INFO                  NSLocalizedString(@"Info", nil)
#define STR_INTERVALS             NSLocalizedString(@"Intervals", nil)
#define STR_INTERVAL_WORKOUTS     NSLocalizedString(@"Interval Workouts", nil)
#define STR_MAP                   NSLocalizedString(@"Map", nil)
#define STR_NEXT                  NSLocalizedString(@"Next", nil)
#define STR_NONE                  NSLocalizedString(@"None", nil)
#define STR_NOT_SYNCHED           NSLocalizedString(@"Not Synched", nil)
#define STR_PACE                  NSLocalizedString(@"Pace", nil)
#define STR_PACE_PLAN             NSLocalizedString(@"Pace Plan", nil)
#define STR_PACE_PLANS            NSLocalizedString(@"Pace Plans", nil)
#define STR_POOL_LENGTH           NSLocalizedString(@"Pool Length", nil)
#define STR_POWER                 NSLocalizedString(@"Power", nil)
#define STR_PREFS                 NSLocalizedString(@"Preferences", nil)
#define STR_PREVIOUS              NSLocalizedString(@"Previous", nil)
#define STR_PROFILE               NSLocalizedString(@"Profile", nil)
#define STR_REPITITIONS           NSLocalizedString(@"Repetitions", nil)
#define STR_REPLACE               NSLocalizedString(@"Replace", nil)
#define STR_SCALE                 NSLocalizedString(@"Scale", nil)
#define STR_SHOE                  NSLocalizedString(@"Shoe", nil)
#define STR_SHOES                 NSLocalizedString(@"Shoes", nil)
#define STR_STARTED               NSLocalizedString(@"Started", nil)
#define STR_SUGGESTED_WORKOUTS    NSLocalizedString(@"Suggested Workouts", nil)
#define STR_SUMMARY               NSLocalizedString(@"Summary", nil)
#define STR_SYNCHED               NSLocalizedString(@"Synched", nil)
#define STR_TIME                  NSLocalizedString(@"Time", nil)
#define STR_WEIGHT                NSLocalizedString(@"Weight", nil)
#define STR_WORKOUT               NSLocalizedString(@"Workout", nil)
#define STR_WORKOUTS              NSLocalizedString(@"Workouts", nil)

#define STR_SECONDS               NSLocalizedString(@"Seconds", nil)
#define STR_METERS                NSLocalizedString(@"Meters", nil)
#define STR_KILOMETERS            NSLocalizedString(@"Kilometers", nil)
#define STR_FEET                  NSLocalizedString(@"Feet", nil)
#define STR_YARDS                 NSLocalizedString(@"Yards", nil)
#define STR_MILES                 NSLocalizedString(@"Miles", nil)
#define STR_SETS                  NSLocalizedString(@"Sets", nil)
#define STR_REPS                  NSLocalizedString(@"Reps", nil)
#define STR_SPLIT_TIMES           NSLocalizedString(@"Split Times", nil)

#define STR_RUNNING               NSLocalizedString(@"Running", nil)
#define STR_CYCLING               NSLocalizedString(@"Cycling", nil)
#define STR_LIFTING               NSLocalizedString(@"Lifting", nil)

#define STR_US_CUSTOMARY          NSLocalizedString(@"US Customary Units", nil)
#define STR_METRIC                NSLocalizedString(@"Metric", nil)

#define STR_REST                  NSLocalizedString(@"Rest", nil)
#define STR_EVENT                 NSLocalizedString(@"Event", nil)
#define STR_SPEED_RUN             NSLocalizedString(@"Speed Run", nil)
#define STR_THRESHOLD_RUN         NSLocalizedString(@"Threshold Run", nil)
#define STR_TEMPO_RUN             NSLocalizedString(@"Tempo Run", nil)
#define STR_EASY_RUN              NSLocalizedString(@"Easy Run", nil)
#define STR_LONG_RUN              NSLocalizedString(@"Long Run", nil)
#define STR_FREE_RUN              NSLocalizedString(@"Free Run", nil)
#define STR_HILL_REPEATS          NSLocalizedString(@"Hill Repeats", nil)
#define STR_FARTLEK_SESSION       NSLocalizedString(@"Fartlek Session", nil)
#define STR_MIDDLE_DISTANCE_RUN   NSLocalizedString(@"Middle Distance Run", nil)
#define STR_HILL_RIDE             NSLocalizedString(@"Hill Ride", nil)
#define STR_INTERVAL_RIDE         NSLocalizedString(@"Interval Ride", nil)
#define STR_TEMPO_RIDE            NSLocalizedString(@"Tempo Ride", nil)
#define STR_EASY_RIDE             NSLocalizedString(@"Easy Ride", nil)
#define STR_SWEET_SPOT_RIDE       NSLocalizedString(@"Sweet Spot Ride", nil)
#define STR_OPEN_WATER_SWIM       NSLocalizedString(@"Open Water Swim", nil)
#define STR_POOL_SWIM             NSLocalizedString(@"Pool Swim", nil)
#define STR_TECHNIQUE_SWIM        NSLocalizedString(@"Technique Swim", nil)

#define STR_MONDAY                NSLocalizedString(@"Monday", nil)
#define STR_TUESDAY               NSLocalizedString(@"Tuesday", nil)
#define STR_WEDNESDAY             NSLocalizedString(@"Wednesday", nil)
#define STR_THURSDAY              NSLocalizedString(@"Thursday", nil)
#define STR_FRIDAY                NSLocalizedString(@"Friday", nil)
#define STR_SATURDAY              NSLocalizedString(@"Saturday", nil)
#define STR_SUNDAY                NSLocalizedString(@"Sunday", nil)

#define STR_TAG                   NSLocalizedString(@"Tag", nil)
#define STR_TAGS                  NSLocalizedString(@"Tags", nil)
#define STR_NEW_TAG               NSLocalizedString(@"New Tag", nil)

#define STR_LOGIN                 NSLocalizedString(@"Login", nil)
#define STR_LOGOUT                NSLocalizedString(@"Log Out", nil)

#define STR_CONNECTED             NSLocalizedString(@"Connected", nil)
#define STR_NOT_CONNECTED         NSLocalizedString(@"Not Connected", nil)

#define STR_RESET_PREFS           NSLocalizedString(@"Reset Settings", nil)
#define STR_RESET_DATA            NSLocalizedString(@"Reset Data", nil)

#define STR_NOT_SET               NSLocalizedString(@"Not Set", nil)
#define STR_NOT_SCHEDULED         NSLocalizedString(@"Not Scheduled", nil)
#define STR_NO_WORKOUTS           NSLocalizedString(@"You have not done any workouts.\nGet moving!", nil)
#define STR_IN_PROGRESS           NSLocalizedString(@"An unfinished activity has been found. Do you wish to resume it?", nil)
#define STR_NO_INTERVAL_WORKOUTS  NSLocalizedString(@"No interval workouts have been created.", nil)
#define STR_DEFINE_POOL_LENGTH    NSLocalizedString(@"Define the length of the swimming pool.", nil)

#define STR_LOW_MEMORY            NSLocalizedString(@"Low memory", nil)
#define STR_MAIL_DISABLED         NSLocalizedString(@"Sending mail is disabled.", nil)
#define STR_EMAIL_CONTENTS        NSLocalizedString(@"The data file is attached.", nil)
#define STR_INTERNAL_ERROR        NSLocalizedString(@"Internal error.", nil)
#define STR_INVALID_OR_NO_INPUT   NSLocalizedString(@"Invalid or no input.", nil)
#define STR_DELETE_FAILED         NSLocalizedString(@"Delete failed!", nil)
#define STR_EXPORT_FAILED         NSLocalizedString(@"Export failed!", nil)
#define STR_EXPORT_SUCCEEDED      NSLocalizedString(@"Export succeeded!", nil)
#define STR_HEALTH_KIT_UNAVAIL    NSLocalizedString(@"HealthKit permissions were not granted. This will limit the application's functionality.", nil)
#define STR_HEALTH_KIT_DENIED     NSLocalizedString(@"HealthKit is unavailable.", nil)

#define SUMMARY_ATTRIBUTE_TOTAL_DISTANCE NSLocalizedString(@"Total Distance", nil)
#define SUMMARY_ATTRIBUTE_MAX_DISTANCE   NSLocalizedString(@"Max. Distance", nil)
#define SUMMARY_ATTRIBUTE_TOTAL_CALORIES NSLocalizedString(@"Total Calories", nil)
#define SUMMARY_ATTRIBUTE_TOTAL_REPS     NSLocalizedString(@"Total Reps", nil)

